version: "3.9"

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-proxy
    ports: ["80:80", "443:443"]
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      oter:
        condition: service_healthy
    restart: always
    networks: [edge]

  oter:
    image: ${IMAGE_REPO}:${IMAGE_TAG}
    environment:
      PORT: "8080"
      LOG_LEVEL: INFO
      # Ensure your image has this file or remove the JAVA_TOOL_OPTIONS line
      JAVA_TOOL_OPTIONS: "-Dlogback.configurationFile=/app/logback.xml"
    expose: ["8080"]
    healthcheck:
      # Ensure curl exists in the image, or switch to wget
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped
    networks: [edge]

networks:
  edge:
    external: true
